### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mattwarkentin** [mattwarkentin/fidelius#1]
- [x] How should I bundle `sodium.js` so the document is self-contained?
- [x] Allow for users to theme the landing page
- [x] Incorrect password prompt
- [x] Make consistent class names and ids for HTML objects
- [x] Favicon support
- [ ] Documentation/vignette
- [x] Touch screen support
- [x] Password hint support
- [x] Show/hide password
